function init(self)
	self.spine_model_id = msg.url(nil, go.get_id("go"), "spinemodel")
	spine.add_skin(self.spine_model_id,"cityfolk_a")
	spine.add_skin(self.spine_model_id,"cityfolk_b")

end

function final(self)

end

function update(self, dt)

end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)

end

function on_reload(self)

end
